-- Create a "profiles" table for storing user data
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  
  -- Onboarding data
  age int,
  gender text,
  height numeric,
  weight numeric,
  blood_type text,
  has_wearable boolean default false,
  wearable_type text,
  
  -- Medical data (Stored as JSON/Arrays)
  medical_history text[],
  chronic_conditions text[],
  medications text[],
  allergies text[],
  
  -- Emergency Contact (JSONB)
  emergency_contact jsonb,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create "health_metrics" table
create table health_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date default current_date,
  steps int default 0,
  heart_rate int,
  sleep_hours numeric(4, 2),
  blood_oxygen int,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table health_metrics enable row level security;

create policy "Users can only see their own health metrics."
  on health_metrics for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own health metrics."
  on health_metrics for insert
  with check ( auth.uid() = user_id );

-- Create "reports" table
create table reports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  file_name text not null,
  file_url text, -- URL if stored in Supabase Storage
  analysis_result jsonb, -- Stores the AI analysis
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table reports enable row level security;

create policy "Users can see their own reports."
  on reports for select
  using ( auth.uid() = user_id );

-- Create "chat_history" table
create table chat_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  message text not null,
  is_bot boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table chat_history enable row level security;

create policy "Users can see their own chat history."
  on chat_history for select
  using ( auth.uid() = user_id );

-- Function to handle new user signup automatically
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
